create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  career_url text,
  source_type text not null,
  last_success_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  company_name text not null,
  company_slug text not null,
  external_id text not null,
  title text not null,
  location text,
  employment_type text,
  department text,
  description text,
  apply_url text not null,
  career_url text,
  source_type text not null,
  posted_at timestamptz,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(company_slug, external_id)
);

create index if not exists jobs_active_idx
  on public.jobs(is_active, last_seen_at desc);

create index if not exists jobs_company_idx
  on public.jobs(company_slug);

create index if not exists jobs_title_idx
  on public.jobs(title);

create index if not exists jobs_location_idx
  on public.jobs(location);

alter table public.jobs enable row level security;
alter table public.companies enable row level security;

drop policy if exists "public can read active jobs" on public.jobs;
create policy "public can read active jobs"
on public.jobs for select
to anon, authenticated
using (is_active = true);

drop policy if exists "public can read companies" on public.companies;
create policy "public can read companies"
on public.companies for select
to anon, authenticated
using (true);

-- The GitHub Action uses the service-role key.
-- Service-role access bypasses RLS; do not expose that key in the frontend.
